package tld

type TldObj struct {
	AlphaOrder string `json:"alpha_order"`
	Tld        []Tdl  `json:"tdl"`
}

type Tdl struct {
	Tld  string `json:"domain"`
	Type string `json:"type"`
}

var Tlds = []TldObj{
	{AlphaOrder: "0",
		Tld: []Tdl{
			{Tld: "0db", Type: "handshake"}, {Tld: "0z", Type: "handshake"},
		},
	},
	{AlphaOrder: "1",
		Tld: []Tdl{
			{Tld: "1", Type: "handshake"}, {Tld: "1d", Type: "handshake"},
			{Tld: "1q", Type: "handshake"},
		},
	},
	{AlphaOrder: "2",
		Tld: []Tdl{
			{Tld: "247", Type: "handshake"},
		},
	},
	{AlphaOrder: "3",
		Tld: []Tdl{
			{Tld: "35", Type: "handshake"}, {Tld: "3dom", Type: "handshake"},
		},
	},
	{AlphaOrder: "4",
		Tld: []Tdl{
			{Tld: "49", Type: "handshake"}, {Tld: "4free", Type: "handshake"},
			{Tld: "4k", Type: "handshake"}, {Tld: "4sale", Type: "handshake"},
			{Tld: "4you", Type: "handshake"},
		},
	},
	{AlphaOrder: "8",
		Tld: []Tdl{
			{Tld: "80proof", Type: "handshake"},
			{Tld: "8888", Type: "handshake"}, {Tld: "8s", Type: "handshake"},
		},
	},
	{AlphaOrder: "a",
		Tld: []Tdl{
			{Tld: "abo", Type: "handshake"}, {Tld: "aboutme", Type: "handshake"},
			{Tld: "aby", Type: "handshake"}, {Tld: "ac", Type: "ccTLD"},
			{Tld: "aca", Type: "handshake"}, {Tld: "academy", Type: "gTLD"},
			{Tld: "accountant ", Type: "gTLD"}, {Tld: "accountants", Type: "gTLD"},
			{Tld: "actor", Type: "gTLD"}, {Tld: "addme", Type: "handshake"},
			{Tld: "adlt", Type: "handshake"}, {Tld: "adult", Type: "gTLD"},
			{Tld: "advisor", Type: "handshake"}, {Tld: "ae.org", Type: "gTLD"},
			{Tld: "afam", Type: "handshake"}, {Tld: "africa", Type: "gTLD"},
			{Tld: "afz", Type: "handshake"}, {Tld: "agency", Type: "gTLD"},
			{Tld: "ags", Type: "handshake"}, {Tld: "agua", Type: "handshake"},
			{Tld: "ahoy", Type: "handshake"}, {Tld: "ai", Type: "ccTLD"},
			{Tld: "airforce", Type: "gTLD"}, {Tld: "aj", Type: "handshake"},
			{Tld: "albums", Type: "handshake"}, {Tld: "alto", Type: "handshake"},
			{Tld: "amg", Type: "handshake"}, {Tld: "amigo", Type: "handshake"},
			{Tld: "amor", Type: "handshake"}, {Tld: "ane", Type: "handshake"},
			{Tld: "annex", Type: "handshake"}, {Tld: "aotearoa", Type: "handshake"},
			{Tld: "apartment", Type: "handshake"}, {Tld: "apartments", Type: "gTLD"},
			{Tld: "api", Type: "handshake"}, {Tld: "app", Type: "gTLD"},
			{Tld: "arbitrator", Type: "handshake"}, {Tld: "army", Type: "gTLD"},
			{Tld: "art ", Type: "gTLD"}, {Tld: "artesanal", Type: "handshake"},
			{Tld: "articles", Type: "handshake"}, {Tld: "artificial", Type: "handshake"},
			{Tld: "asia", Type: "gTLD"}, {Tld: "associates", Type: "gTLD"},
			{Tld: "assurances", Type: "handshake"}, {Tld: "atc", Type: "handshake"},
			{Tld: "ath", Type: "handshake"}, {Tld: "attorney", Type: "gTLD"},
			{Tld: "atwork", Type: "handshake"}, {Tld: "auction", Type: "gTLD"},
			{Tld: "audio", Type: "gTLD"}, {Tld: "augmented", Type: "handshake"},
			{Tld: "auto", Type: "gTLD"}, {Tld: "autos", Type: "gTLD"},
		},
	},
	{AlphaOrder: "b",
		Tld: []Tdl{
			{Tld: "b2b", Type: "handshake"}, {Tld: "baas", Type: "handshake"},
			{Tld: "baby", Type: "gTLD"}, {Tld: "badly", Type: "handshake"},
			{Tld: "bakes", Type: "handshake"}, {Tld: "band", Type: "gTLD"},
			{Tld: "bar", Type: "gTLD"}, {Tld: "bargains", Type: "gTLD"},
			{Tld: "batch", Type: "handshake"}, {Tld: "beach", Type: "handshake"},
			{Tld: "beauty", Type: "gTLD"}, {Tld: "beef", Type: "handshake"},
			{Tld: "beer", Type: "gTLD"}, {Tld: "bem", Type: "handshake"},
			{Tld: "berlin", Type: "gTLD"}, {Tld: "best", Type: "gTLD"},
			{Tld: "bid", Type: "gTLD"}, {Tld: "bike", Type: "gTLD"},
			{Tld: "bingo", Type: "gTLD"}, {Tld: "bio", Type: "gTLD"},
			{Tld: "biometric", Type: "handshake"}, {Tld: "bitcoinfund", Type: "handshake"},
			{Tld: "biz", Type: "gTLD"}, {Tld: "bizdata", Type: "handshake"},
			{Tld: "bizdev", Type: "handshake"}, {Tld: "black", Type: "gTLD"},
			{Tld: "blackfriday", Type: "gTLD"}, {Tld: "blockchaindapps", Type: "handshake"},
			{Tld: "blog", Type: "gTLD"}, {Tld: "blogging", Type: "handshake"},
			{Tld: "blue", Type: "gTLD"}, {Tld: "bmp", Type: "handshake"},
			{Tld: "boats", Type: "gTLD"}, {Tld: "bob", Type: "handshake"},
			{Tld: "bog", Type: "handshake"}, {Tld: "bond", Type: "gTLD"},
			{Tld: "boo", Type: "gTLD"}, {Tld: "booked", Type: "handshake"},
			{Tld: "boredapes", Type: "handshake"}, {Tld: "boston", Type: "gTLD"},
			{Tld: "boutique", Type: "gTLD"}, {Tld: "bqw", Type: "handshake"},
			{Tld: "br.com", Type: "gTLD"}, {Tld: "brand", Type: "handshake"},
			{Tld: "brewery", Type: "handshake"}, {Tld: "brokers", Type: "handshake"},
			{Tld: "browsers", Type: "handshake"}, {Tld: "btk9", Type: "handshake"},
			{Tld: "btt", Type: "handshake"}, {Tld: "buddhist", Type: "handshake"},
			{Tld: "build", Type: "gTLD"}, {Tld: "builders", Type: "gTLD"},
			{Tld: "business", Type: "gTLD"}, {Tld: "buyaflat", Type: "handshake"},
			{Tld: "buzz", Type: "gTLD"}, {Tld: "byn", Type: "handshake"},
			{Tld: "bz", Type: "ccTLD"},
		},
	},
	{AlphaOrder: "c",
		Tld: []Tdl{
			{Tld: "c", Type: "handshake"}, {Tld: "c0m", Type: "handshake"},
			{Tld: "c4", Type: "handshake"}, {Tld: "ca", Type: "ccTLD"},
			{Tld: "cab", Type: "gTLD"}, {Tld: "cabins", Type: "handshake"},
			{Tld: "cafe", Type: "gTLD"}, {Tld: "cam", Type: "gTLD"},
			{Tld: "camera", Type: "gTLD"}, {Tld: "camp", Type: "gTLD"},
			{Tld: "capital", Type: "gTLD"}, {Tld: "car", Type: "gTLD"},
			{Tld: "cardcollector", Type: "handshake"}, {Tld: "cards", Type: "gTLD"},
			{Tld: "care", Type: "gTLD"}, {Tld: "careers", Type: "gTLD"},
			{Tld: "cares", Type: "handshake"}, {Tld: "cars", Type: "gTLD"},
			{Tld: "casa", Type: "gTLD"}, {Tld: "cash", Type: "gTLD"},
			{Tld: "casino", Type: "gTLD"}, {Tld: "catering", Type: "gTLD"},
			{Tld: "catgirl", Type: "handshake"}, {Tld: "causes", Type: "handshake"},
			{Tld: "cc", Type: "ccTLD"}, {Tld: "center", Type: "gTLD"},
			{Tld: "ceo", Type: "gTLD"}, {Tld: "cerrajero", Type: "handshake"},
			{Tld: "cfd", Type: "gTLD"}, {Tld: "ch", Type: "gTLD"},
			{Tld: "chat", Type: "gTLD"}, {Tld: "cheap", Type: "gTLD"},
			{Tld: "cheddar", Type: "handshake"}, {Tld: "christmas", Type: "gTLD"},
			{Tld: "cism", Type: "handshake"}, {Tld: "cita", Type: "handshake"},
			{Tld: "citizenship", Type: "handshake"}, {Tld: "city", Type: "gTLD"},
			{Tld: "ckq", Type: "handshake"}, {Tld: "claims", Type: "gTLD"},
			{Tld: "clc", Type: "handshake"}, {Tld: "cleaning", Type: "gTLD"},
			{Tld: "clic", Type: "handshake"}, {Tld: "click", Type: "gTLD"},
			{Tld: "client", Type: "handshake"}, {Tld: "clients", Type: "handshake"},
			{Tld: "clinic", Type: "gTLD"}, {Tld: "cliq", Type: "handshake"},
			{Tld: "clothing", Type: "gTLD"}, {Tld: "cloud", Type: "gTLD"},
			{Tld: "cloudbot", Type: "handshake"}, {Tld: "club", Type: "gTLD"},
			{Tld: "cm", Type: "ccTLD"}, {Tld: "cm3", Type: "handshake"},
			{Tld: "cn", Type: "ccTLD"}, {Tld: "cn.com", Type: "gTLD"},
			{Tld: "cn3", Type: "handshake"}, {Tld: "co", Type: "ccTLD"},
			{Tld: "co.bz", Type: "ccTLD"}, {Tld: "co.com", Type: "gTLD"},
			{Tld: "co.in", Type: "ccTLD"}, {Tld: "co.uk", Type: "ccTLD"},
			{Tld: "co3", Type: "handshake"}, {Tld: "coach", Type: "gTLD"},
			{Tld: "codes", Type: "gTLD"}, {Tld: "codeschool", Type: "handshake"},
			{Tld: "coffee", Type: "gTLD"}, {Tld: "coffees", Type: "handshake"},
			{Tld: "coinnet", Type: "handshake"}, {Tld: "college", Type: "gTLD"},
			{Tld: "com", Type: "gTLD"}, {Tld: "com.au", Type: "ccTLD"},
			{Tld: "com.cn", Type: "ccTLD"}, {Tld: "com.co", Type: "ccTLD"},
			{Tld: "com.de", Type: "gTLD"}, {Tld: "com.es", Type: "ccTLD"},
			{Tld: "com.mx", Type: "ccTLD"}, {Tld: "com.pe", Type: "ccTLD"},
			{Tld: "com.ph", Type: "ccTLD"}, {Tld: "com.se", Type: "gTLD"},
			{Tld: "com.sg", Type: "ccTLD"}, {Tld: "com.vc", Type: "ccTLD"},
			{Tld: "comic", Type: "handshake"}, {Tld: "comics", Type: "handshake"},
			{Tld: "commerce", Type: "handshake"}, {Tld: "communion", Type: "handshake"},
			{Tld: "community", Type: "gTLD"}, {Tld: "company", Type: "gTLD"},
			{Tld: "complete", Type: "handshake"}, {Tld: "computer", Type: "gTLD"},
			{Tld: "computers", Type: "handshake"}, {Tld: "concise", Type: "handshake"},
			{Tld: "condos", Type: "gTLD"}, {Tld: "conduct", Type: "handshake"},
			{Tld: "conductor", Type: "handshake"}, {Tld: "conf", Type: "handshake"},
			{Tld: "connectors", Type: "handshake"}, {Tld: "connoisseur", Type: "handshake"},
			{Tld: "construction", Type: "gTLD"}, {Tld: "consultancy", Type: "handshake"},
			{Tld: "consulting", Type: "gTLD"}, {Tld: "contact", Type: "gTLD"},
			{Tld: "contractors", Type: "gTLD"}, {Tld: "cooking", Type: "gTLD"},
			{Tld: "cool", Type: "gTLD"}, {Tld: "cork", Type: "handshake"},
			{Tld: "corporation", Type: "handshake"}, {Tld: "country", Type: "gTLD"},
			{Tld: "coupons", Type: "gTLD"}, {Tld: "courses", Type: "gTLD"},
			{Tld: "crazy", Type: "handshake"}, {Tld: "creations", Type: "handshake"},
			{Tld: "creativity", Type: "handshake"}, {Tld: "creator", Type: "handshake"},
			{Tld: "credit", Type: "gTLD"}, {Tld: "creditcard", Type: "gTLD"},
			{Tld: "crew", Type: "handshake"}, {Tld: "cricket", Type: "gTLD"},
			{Tld: "croatia", Type: "handshake"}, {Tld: "cruises", Type: "gTLD"},
			{Tld: "cryp", Type: "handshake"}, {Tld: "cryptobets", Type: "handshake"},
			{Tld: "cryptogamer", Type: "handshake"}, {Tld: "cryptoservice", Type: "handshake"},
			{Tld: "cuba", Type: "handshake"}, {Tld: "cx", Type: "ccTLD"},
			{Tld: "cycle", Type: "handshake"}, {Tld: "cymru", Type: "gTLD"},
			{Tld: "cyou", Type: "gTLD"}, {Tld: "cyprus", Type: "handshake"},
		},
	},
	{AlphaOrder: "d",
		Tld: []Tdl{
			{Tld: "d5", Type: "handshake"}, {Tld: "d8", Type: "handshake"},
			{Tld: "dias", Type: "handshake"}, {Tld: "damn", Type: "handshake"},
			{Tld: "dan", Type: "handshake"}, {Tld: "dance", Type: "gTLD"},
			{Tld: "datamining", Type: "handshake"}, {Tld: "date", Type: "gTLD"},
			{Tld: "dating", Type: "gTLD"}, {Tld: "day", Type: "gTLD"},
			{Tld: "daytrade", Type: "handshake"}, {Tld: "dco", Type: "handshake"},
			{Tld: "de", Type: "ccTLD"}, {Tld: "de.com", Type: "gTLD"},
			{Tld: "de3", Type: "handshake"}, {Tld: "deals", Type: "gTLD"},
			{Tld: "dean", Type: "handshake"}, {Tld: "debtless", Type: "handshake"},
			{Tld: "decent", Type: "handshake"}, {Tld: "decentralize", Type: "handshake"},
			{Tld: "defi", Type: "handshake"}, {Tld: "deficit", Type: "handshake"},
			{Tld: "degen", Type: "handshake"}, {Tld: "degree", Type: "gTLD"},
			{Tld: "delivery", Type: "gTLD"}, {Tld: "democrat", Type: "gTLD"},
			{Tld: "den", Type: "gTLD"}, {Tld: "dental", Type: "gTLD"},
			{Tld: "dentist", Type: "gTLD"}, {Tld: "desi", Type: "gTLD"},
			{Tld: "design", Type: "gTLD"}, {Tld: "detour", Type: "handshake"},
			{Tld: "dev", Type: "gTLD"}, {Tld: "development", Type: "handshake"},
			{Tld: "dg", Type: "handshake"}, {Tld: "dh", Type: "handshake"},
			{Tld: "diamonds", Type: "gTLD"}, {Tld: "dids", Type: "handshake"},
			{Tld: "diet", Type: "gTLD"}, {Tld: "digital", Type: "gTLD"},
			{Tld: "digitalasset", Type: "handshake"}, {Tld: "dilate", Type: "handshake"},
			{Tld: "direct", Type: "gTLD"}, {Tld: "directive", Type: "handshake"},
			{Tld: "directory", Type: "gTLD"}, {Tld: "discounts", Type: "handshake"},
			{Tld: "discussion", Type: "handshake"}, {Tld: "diva", Type: "handshake"},
			{Tld: "dlt", Type: "handshake"}, {Tld: "dly", Type: "handshake"},
			{Tld: "doctor", Type: "gTLD"}, {Tld: "dog", Type: "gTLD"},
			{Tld: "doge", Type: "handshake"}, {Tld: "dogecoin", Type: "handshake"},
			{Tld: "dojo", Type: "handshake"}, {Tld: "dolls", Type: "handshake"},
			{Tld: "doma", Type: "handshake"}, {Tld: "domains", Type: "gTLD"},
			{Tld: "dookie", Type: "handshake"}, {Tld: "down", Type: "handshake"},
			{Tld: "download", Type: "gTLD"}, {Tld: "downloads", Type: "handshake"},
			{Tld: "ds", Type: "handshake"}, {Tld: "ducktape", Type: "handshake"},
			{Tld: "duration", Type: "handshake"}, {Tld: "dvd", Type: "handshake"},
			{Tld: "dweb", Type: "handshake"}, {Tld: "dweb3", Type: "handshake"},
			{Tld: "dy", Type: "handshake"},
		},
	},
	{AlphaOrder: "e",
		Tld: []Tdl{
			{Tld: "earth", Type: "handshake"}, {Tld: "eathere", Type: "handshake"},
			{Tld: "eco", Type: "gTLD"}, {Tld: "economics", Type: "handshake"},
			{Tld: "economy", Type: "handshake"}, {Tld: "edm", Type: "handshake"},
			{Tld: "education", Type: "gTLD"}, {Tld: "egame", Type: "handshake"},
			{Tld: "elect", Type: "handshake"}, {Tld: "electronics", Type: "handshake"},
			{Tld: "elite", Type: "handshake"}, {Tld: "email", Type: "gTLD"},
			{Tld: "emj", Type: "handshake"}, {Tld: "energy", Type: "gTLD"},
			{Tld: "engaged", Type: "handshake"}, {Tld: "engineer", Type: "gTLD"},
			{Tld: "engineering", Type: "gTLD"}, {Tld: "enterprises", Type: "gTLD"},
			{Tld: "ep", Type: "handshake"}, {Tld: "eporn", Type: "handshake"},
			{Tld: "equipment", Type: "gTLD"}, {Tld: "ero", Type: "handshake"},
			{Tld: "es", Type: "handshake"}, {Tld: "estate", Type: "gTLD"},
			{Tld: "estates", Type: "handshake"}, {Tld: "enternity", Type: "handshake"},
			{Tld: "etickets", Type: "handshake"}, {Tld: "eu", Type: "ccTLD"},
			{Tld: "eu.com", Type: "gTLD"}, {Tld: "event", Type: "handshake"},
			{Tld: "events", Type: "gTLD"}, {Tld: "ewallet", Type: "handshake"},
			{Tld: "ewx", Type: "handshake"}, {Tld: "exchange", Type: "gTLD"},
			{Tld: "executive", Type: "handshake"}, {Tld: "expert", Type: "gTLD"},
			{Tld: "exposed", Type: "gTLD"}, {Tld: "express", Type: "gTLD"},
			{Tld: "ext", Type: "handshake"}, {Tld: "exu", Type: "handshake"},
			{Tld: "eyecare", Type: "handshake"}, {Tld: "ez", Type: "handshake"},
		},
	},
	{AlphaOrder: "f",
		Tld: []Tdl{
			{Tld: "fail", Type: "gTLD"}, {Tld: "faith", Type: "gTLD"},
			{Tld: "fak", Type: "handshake"}, {Tld: "fam", Type: "handshake"},
			{Tld: "family", Type: "gTLD"}, {Tld: "fans", Type: "gTLD"},
			{Tld: "faqs", Type: "handshake"}, {Tld: "farm", Type: "gTLD"},
			{Tld: "fashion", Type: "gTLD"}, {Tld: "fcb", Type: "handshake"},
			{Tld: "fd", Type: "handshake"}, {Tld: "fe", Type: "handshake"},
			{Tld: "feedback", Type: "gTLD"}, {Tld: "feeling", Type: "handshake"},
			{Tld: "fej", Type: "handshake"}, {Tld: "fellowship", Type: "handshake"},
			{Tld: "ffa", Type: "handshake"}, {Tld: "fgz", Type: "handshake"},
			{Tld: "fia", Type: "handshake"}, {Tld: "fiat2btc", Type: "handshake"},
			{Tld: "fiji", Type: "handshake"}, {Tld: "film", Type: "gTLD"},
			{Tld: "filters", Type: "handshake"}, {Tld: "finance", Type: "gTLD"},
			{Tld: "financial", Type: "gTLD"}, {Tld: "financialnews", Type: "handshake"},
			{Tld: "findme", Type: "handshake"}, {Tld: "firstname", Type: "handshake"},
			{Tld: "fish", Type: "gTLD"}, {Tld: "fishing", Type: "gTLD"},
			{Tld: "fit", Type: "gTLD"}, {Tld: "fitness", Type: "gTLD"},
			{Tld: "fl3x", Type: "handshake"}, {Tld: "flap", Type: "handshake"},
			{Tld: "flat", Type: "handshake"}, {Tld: "flights", Type: "gTLD"},
			{Tld: "florist", Type: "gTLD"}, {Tld: "flowers", Type: "gTLD"},
			{Tld: "fm", Type: "ccTLD"}, {Tld: "fmw", Type: "handshake"},
			{Tld: "follow", Type: "handshake"}, {Tld: "foot", Type: "handshake"},
			{Tld: "football", Type: "gTLD"}, {Tld: "forall", Type: "handshake"},
			{Tld: "fore", Type: "handshake"}, {Tld: "forsale", Type: "gTLD"},
			{Tld: "forum", Type: "gTLD"}, {Tld: "foundation", Type: "gTLD"},
			{Tld: "fr", Type: "ccTLD"}, {Tld: "freebies", Type: "handshake"},
			{Tld: "fua", Type: "handshake"}, {Tld: "fun", Type: "gTLD"},
			{Tld: "fund", Type: "gTLD"}, {Tld: "fundraising", Type: "handshake"},
			{Tld: "furniture", Type: "gTLD"}, {Tld: "futbol", Type: "gTLD"},
			{Tld: "fw", Type: "handshake"}, {Tld: "fwd", Type: "handshake"},
			{Tld: "fyi", Type: "gTLD"},
		},
	},
	{AlphaOrder: "g",
		Tld: []Tdl{
			{Tld: "gad", Type: "handshake"}, {Tld: "gadget", Type: "handshake"},
			{Tld: "gallery", Type: "gTLD"}, {Tld: "game", Type: "gTLD"},
			{Tld: "games", Type: "gTLD"}, {Tld: "garden", Type: "gTLD"},
			{Tld: "gay", Type: "gTLD"}, {Tld: "gb.net", Type: "gTLD"},
			{Tld: "gdl", Type: "handshake"}, {Tld: "gdn", Type: "gTLD"},
			{Tld: "ger", Type: "handshake"}, {Tld: "gethigh", Type: "handshake"},
			{Tld: "getreal", Type: "handshake"}, {Tld: "getwell", Type: "handshake"},
			{Tld: "gg", Type: "ccTLD"}, {Tld: "gic", Type: "gTLD"},
			{Tld: "gift", Type: "gTLD"}, {Tld: "gifts", Type: "gTLD"},
			{Tld: "gin", Type: "handshake"}, {Tld: "giveaways", Type: "handshake"},
			{Tld: "gives", Type: "gTLD"}, {Tld: "glass", Type: "gTLD"},
			{Tld: "global", Type: "gTLD"}, {Tld: "gmbh", Type: "gTLD"},
			{Tld: "gofor", Type: "handshake"}, {Tld: "gold", Type: "gTLD"},
			{Tld: "golf", Type: "gTLD"}, {Tld: "gon", Type: "handshake"},
			{Tld: "gonow", Type: "handshake"}, {Tld: "goth", Type: "handshake"},
			{Tld: "gr.com", Type: "gTLD"}, {Tld: "grandmaster", Type: "handshake"},
			{Tld: "graphics", Type: "gTLD"}, {Tld: "gratis", Type: "gTLD"},
			{Tld: "greatoffers", Type: "handshake"}, {Tld: "green", Type: "gTLD"},
			{Tld: "gripe", Type: "gTLD"}, {Tld: "ground", Type: "gTLD"},
			{Tld: "grow", Type: "handshake"}, {Tld: "gruppen", Type: "handshake"},
			{Tld: "guey", Type: "handshake"}, {Tld: "guidance", Type: "handshake"},
			{Tld: "guide", Type: "gTLD"}, {Tld: "guitars", Type: "gTLD"},
			{Tld: "guru", Type: "gTLD"}, {Tld: "guz", Type: "handshake"},
			{Tld: "gvz", Type: "handshake"}, {Tld: "gyc", Type: "handshake"},
			{Tld: "gzp", Type: "handshake"},
		},
	},
	{AlphaOrder: "h",
		Tld: []Tdl{
			{Tld: "hack", Type: "handshake"}, {Tld: "hackathon", Type: "handshake"},
			{Tld: "hae", Type: "handshake"}, {Tld: "hah", Type: "handshake"},
			{Tld: "hair", Type: "gTLD"}, {Tld: "haiti", Type: "gTLD"},
			{Tld: "hamburg", Type: "gTLD"}, {Tld: "hardrive", Type: "handshake"},
			{Tld: "haus", Type: "gTLD"}, {Tld: "hb", Type: "handshake"},
			{Tld: "health", Type: "gTLD"}, {Tld: "healthcare", Type: "gTLD"},
			{Tld: "heh", Type: "handshake"}, {Tld: "hell", Type: "handshake"},
			{Tld: "help", Type: "gTLD"}, {Tld: "helpdesk", Type: "handshake"},
			{Tld: "hem", Type: "handshake"}, {Tld: "hermanos", Type: "handshake"},
			{Tld: "gin", Type: "handshake"}, {Tld: "giveaways", Type: "handshake"},
			{Tld: "hf", Type: "handshake"}, {Tld: "hgo", Type: "handshake"},
			{Tld: "hill", Type: "handshake"}, {Tld: "hiphop", Type: "gTLD"},
			{Tld: "hire", Type: "handshake"}, {Tld: "hits", Type: "gTLD"},
			{Tld: "hockey", Type: "gTLD"}, {Tld: "hodlr", Type: "handshake"},
			{Tld: "holding", Type: "handshake"}, {Tld: "holdings", Type: "gTLD"},
			{Tld: "holiday", Type: "gTLD"}, {Tld: "holidayrental", Type: "handshake"},
			{Tld: "holidays", Type: "handshake"}, {Tld: "homes", Type: "gTLD"},
			{Tld: "hometown", Type: "handshake"}, {Tld: "horny", Type: "handshake"},
			{Tld: "horse", Type: "gTLD"}, {Tld: "host", Type: "gTLD"},
			{Tld: "hosting", Type: "gTLD"}, {Tld: "hotelguide", Type: "handshake"},
			{Tld: "house", Type: "gTLD"}, {Tld: "how", Type: "gTLD"},
			{Tld: "hpp", Type: "handshake"}, {Tld: "hsu", Type: "handshake"},
			{Tld: "hu.net", Type: "gTLD"}, {Tld: "hx", Type: "handshake"},
		},
	},
	{AlphaOrder: "i",
		Tld: []Tdl{
			{Tld: "i1", Type: "handshake"}, {Tld: "ib", Type: "handshake"},
			{Tld: "ibn", Type: "handshake"}, {Tld: "icu", Type: "gTLD"},
			{Tld: "id", Type: "ccTLD"}, {Tld: "ieh", Type: "handshake"},
			{Tld: "ifv", Type: "handshake"}, {Tld: "ih", Type: "handshake"},
			{Tld: "ik", Type: "handshake"}, {Tld: "ill", Type: "handshake"},
			{Tld: "iloveu", Type: "handshake"}, {Tld: "immo", Type: "gTLD"},
			{Tld: "immobilien", Type: "gTLD"}, {Tld: "in", Type: "ccTLD"},
			{Tld: "in.net", Type: "gTLD"}, {Tld: "inc", Type: "gTLD"},
			{Tld: "income", Type: "handshake"}, {Tld: "industries", Type: "gTLD"},
			{Tld: "influencer", Type: "handshake"}, {Tld: "info", Type: "gTLD"},
			{Tld: "information", Type: "handshake"}, {Tld: "inh", Type: "handshake"},
			{Tld: "ink", Type: "gTLD"}, {Tld: "innovator", Type: "handshake"},
			{Tld: "institute", Type: "gTLD"}, {Tld: "insure", Type: "gTLD"},
			{Tld: "interest", Type: "handshake"}, {Tld: "international", Type: "gTLD"},
			{Tld: "intro", Type: "handshake"}, {Tld: "investments", Type: "gTLD"},
			{Tld: "iny", Type: "handshake"}, {Tld: "io", Type: "ccTLD"},
			{Tld: "ioi", Type: "handshake"}, {Tld: "ioo", Type: "handshake"},
			{Tld: "irish", Type: "gTLD"}, {Tld: "is", Type: "ccTLD"},
			{Tld: "island", Type: "handshake"}, {Tld: "ism", Type: "handshake"},
			{Tld: "isthefuture", Type: "handshake"}, {Tld: "italy", Type: "handshake"},
			{Tld: "iuh", Type: "handshake"}, {Tld: "iurl", Type: "handshake"},
			{Tld: "iw", Type: "handshake"}, {Tld: "ize", Type: "handshake"},
		},
	},
	{AlphaOrder: "j",
		Tld: []Tdl{
			{Tld: "ja", Type: "handshake"}, {Tld: "january", Type: "handshake"},
			{Tld: "jao", Type: "handshake"}, {Tld: "jeh", Type: "handshake"},
			{Tld: "jetzt", Type: "gTLD"}, {Tld: "jewelry", Type: "gTLD"},
			{Tld: "jf", Type: "handshake"}, {Tld: "job", Type: "handshake"},
			{Tld: "jok", Type: "handshake"}, {Tld: "joker", Type: "handshake"},
			{Tld: "jov", Type: "handshake"}, {Tld: "jp.net", Type: "ccTLD"},
			{Tld: "jpg", Type: "handshake"}, {Tld: "jpgs", Type: "handshake"},
			{Tld: "jpn.com", Type: "gTLD"}, {Tld: "js", Type: "handshake"},
			{Tld: "jub", Type: "handshake"}, {Tld: "juegos", Type: "gTLD"},
			{Tld: "jugar", Type: "handshake"}, {Tld: "jun", Type: "handshake"},
			{Tld: "jy", Type: "handshake"},
		},
	},
	{AlphaOrder: "k",
		Tld: []Tdl{
			{Tld: "kaufen", Type: "gTLD"}, {Tld: "kcx", Type: "handshake"},
			{Tld: "kennel", Type: "handshake"}, {Tld: "keys", Type: "handshake"},
			{Tld: "kf", Type: "handshake"}, {Tld: "kicks", Type: "handshake"},
			{Tld: "kids", Type: "gTLD"}, {Tld: "kim", Type: "gTLD"},
			{Tld: "kinetic", Type: "handshake"}, {Tld: "kip", Type: "handshake"},
			{Tld: "kitchen", Type: "gTLD"}, {Tld: "kiwi", Type: "gTLD"},
			{Tld: "kj", Type: "handshake"}, {Tld: "kl", Type: "handshake"},
			{Tld: "knight", Type: "handshake"}, {Tld: "knowledge", Type: "handshake"},
			{Tld: "kq", Type: "handshake"}, {Tld: "krd", Type: "gTLD"},
			{Tld: "ks", Type: "handshake"}, {Tld: "kv", Type: "handshake"},
			{Tld: "kyoto", Type: "gTLD"},
		},
	},
	{AlphaOrder: "l",
		Tld: []Tdl{
			{Tld: "l33t", Type: "handshake"}, {Tld: "la", Type: "ccTLD"},
			{Tld: "land", Type: "gTLD"}, {Tld: "lars", Type: "handshake"},
			{Tld: "lat", Type: "gTLD"}, {Tld: "lausanne", Type: "handshake"},
			{Tld: "law", Type: "gTLD"}, {Tld: "lawexpert", Type: "handshake"},
			{Tld: "lawoffice", Type: "handshake"}, {Tld: "lawsuit", Type: "handshake"},
			{Tld: "lawyer", Type: "gTLD"}, {Tld: "lean", Type: "handshake"},
			{Tld: "lease", Type: "gTLD"}, {Tld: "legal", Type: "gTLD"},
			{Tld: "legendary", Type: "handshake"}, {Tld: "lgbt", Type: "gTLD"},
			{Tld: "li", Type: "ccTLD"}, {Tld: "life", Type: "gTLD"},
			{Tld: "lighting", Type: "gTLD"}, {Tld: "likeapro", Type: "handshake"},
			{Tld: "limited", Type: "gTLD"}, {Tld: "limo", Type: "gTLD"},
			{Tld: "lingo", Type: "handshake"}, {Tld: "link", Type: "gTLD"},
			{Tld: "live", Type: "gTLD"}, {Tld: "livestreaming", Type: "handshake"},
			{Tld: "ljb", Type: "handshake"}, {Tld: "llc", Type: "gTLD"},
			{Tld: "lli", Type: "handshake"}, {Tld: "lnx", Type: "handshake"},
			{Tld: "lo", Type: "handshake"}, {Tld: "loan", Type: "gTLD"},
			{Tld: "loans", Type: "gTLD"}, {Tld: "logo", Type: "handshake"},
			{Tld: "lol", Type: "gTLD"}, {Tld: "london", Type: "gTLD"},
			{Tld: "lord", Type: "handshake"}, {Tld: "lov", Type: "handshake"},
			{Tld: "love", Type: "gTLD"}, {Tld: "lovesyou", Type: "handshake"},
			{Tld: "ltd", Type: "gTLD"}, {Tld: "ltda", Type: "gTLD"},
			{Tld: "luxury", Type: "gTLD"}, {Tld: "lw", Type: "handshake"},
			{Tld: "lyf", Type: "handshake"}, {Tld: "lz", Type: "handshake"},
		},
	},
	{AlphaOrder: "m",
		Tld: []Tdl{
			{Tld: "maestro", Type: "handshake"}, {Tld: "magazine", Type: "handshake"},
			{Tld: "maison", Type: "gTLD"}, {Tld: "makeup", Type: "gTLD"},
			{Tld: "management", Type: "gTLD"}, {Tld: "mansion", Type: "handshake"},
			{Tld: "market", Type: "gTLD"}, {Tld: "marketing", Type: "gTLD"},
			{Tld: "mba", Type: "gTLD"}, {Tld: "me", Type: "ccTLD"},
			{Tld: ".me.uk", Type: "ccTLD"}, {Tld: "media", Type: "gTLD"},
			{Tld: "mediator", Type: "handshake"}, {Tld: "medico", Type: "handshake"},
			{Tld: "mee", Type: "handshake"}, {Tld: "melbourne", Type: "gTLD"},
			{Tld: "memorial", Type: "gTLD"}, {Tld: "men", Type: "gTLD"},
			{Tld: "ment", Type: "handshake"}, {Tld: "menu", Type: "gTLD"},
			{Tld: "merc", Type: "handshake"}, {Tld: "mev", Type: "handshake"},
			{Tld: "mex.com", Type: "gTLD"}, {Tld: "miami", Type: "gTLD"},
			{Tld: "micro", Type: "handshake"}, {Tld: "mined", Type: "handshake"},
			{Tld: "mission", Type: "handshake"}, {Tld: "mke", Type: "handshake"},
			{Tld: "moar", Type: "handshake"}, {Tld: "mobi", Type: "gTLD"},
			{Tld: "moda", Type: "gTLD"}, {Tld: "moe", Type: "gTLD"},
			{Tld: "mom", Type: "gTLD"}, {Tld: "mommy", Type: "handshake"},
			{Tld: "money", Type: "gTLD"}, {Tld: "monster", Type: "gTLD"},
			{Tld: "montage", Type: "handshake"}, {Tld: "mooning", Type: "handshake"},
			{Tld: "mortgage", Type: "gTLD"}, {Tld: "motherboard", Type: "handshake"},
			{Tld: "motorcycles", Type: "gTLD"}, {Tld: "movies", Type: "gTLD"},
			{Tld: "mtl", Type: "handshake"}, {Tld: "mvo", Type: "handshake"},
			{Tld: "mwallet", Type: "handshake"}, {Tld: "mx", Type: "ccTLD"},
			{Tld: "mycard", Type: "handshake"}, {Tld: "myco", Type: "handshake"},
			{Tld: "myo", Type: "handshake"}, {Tld: "myproxy", Type: "handshake"},
			{Tld: "myurl", Type: "handshake"},
		},
	},
	{AlphaOrder: "n",
		Tld: []Tdl{
			{Tld: "nagoya", Type: "gTLD"}, {Tld: "nah", Type: "handshake"},
			{Tld: "name", Type: "gTLD"}, {Tld: "napavalley", Type: "handshake"},
			{Tld: "navy", Type: "gTLD"}, {Tld: "nearme", Type: "handshake"},
			{Tld: "neo", Type: "handshake"}, {Tld: "nerdy", Type: "handshake"},
			{Tld: "net", Type: "gTLD"}, {Tld: "net.au", Type: "ccTLD"},
			{Tld: "net.cn", Type: "ccTLD"}, {Tld: "net.pe", Type: "ccTLD"},
			{Tld: "net.ph", Type: "ccTLD"}, {Tld: "net.vc", Type: "ccTLD"},
			{Tld: "network", Type: "gTLD"}, {Tld: "new", Type: "gTLD"},
			{Tld: "news", Type: "gTLD"}, {Tld: "nftcartel", Type: "handshake"},
			{Tld: "nfts", Type: "handshake"}, {Tld: "ngo", Type: "gTLD"},
			{Tld: "nil", Type: "handshake"}, {Tld: "ninja", Type: "gTLD"},
			{Tld: "nl", Type: "ccTLD"}, {Tld: "nod", Type: "handshake"},
			{Tld: "nom", Type: "handshake"}, {Tld: "nom.es", Type: "ccTLD"},
			{Tld: "notes", Type: "handshake"}, {Tld: "nouns", Type: "handshake"},
			{Tld: "npm", Type: "handshake"}, {Tld: "nu", Type: "ccTLD"},
			{Tld: "nuk", Type: "handshake"}, {Tld: "numb", Type: "handshake"},
			{Tld: "nxs", Type: "handshake"}, {Tld: "nyc", Type: "gTLD"},
			{Tld: "nym", Type: "handshake"},
		},
	},
	{AlphaOrder: "o",
		Tld: []Tdl{
			{Tld: "ob", Type: "handshake"}, {Tld: "observer", Type: "gTLD"},
			{Tld: "od", Type: "handshake"}, {Tld: "oda", Type: "handshake"},
			{Tld: "oflinewallet", Type: "handshake"}, {Tld: "mansion", Type: "handshake"},
			{Tld: "often", Type: "handshake"}, {Tld: "oh", Type: "handshake"},
			{Tld: "ohmy", Type: "handshake"}, {Tld: "oin", Type: "handshake"},
			{Tld: ".okinawa", Type: "gTLD"}, {Tld: "oncam", Type: "handshake"},
			{Tld: "one", Type: "gTLD"}, {Tld: "onewallet", Type: "handshake"},
			{Tld: "ong", Type: "gTLD"}, {Tld: "onl", Type: "gTLD"},
			{Tld: "online", Type: "gTLD"}, {Tld: "onlinenews", Type: "handshake"},
			{Tld: "oo", Type: "handshake"}, {Tld: "oof", Type: "handshake"},
			{Tld: "oot", Type: "handshake"}, {Tld: "optimize", Type: "handshake"},
			{Tld: "oq", Type: "handshake"}, {Tld: "orb", Type: "handshake"},
			{Tld: "org", Type: "gTLD"}, {Tld: "org.au", Type: "ccTLD"},
			{Tld: "org.cn", Type: "ccTLD"}, {Tld: "org.es", Type: "ccTLD"},
			{Tld: "org.mx", Type: "ccTLD"}, {Tld: "org.pe", Type: "ccTLD"},
			{Tld: "org.ph", Type: "ccTLD"}, {Tld: "org.uk", Type: "ccTLD"},
			{Tld: "org.vc", Type: "ccTLD"}, {Tld: "osaka", Type: "gTLD"},
			{Tld: "oslo", Type: "handshake"}, {Tld: "ot", Type: "handshake"},
			{Tld: "oun", Type: "handshake"}, {Tld: "owbo", Type: "handshake"},
		},
	},
	{AlphaOrder: "p",
		Tld: []Tdl{
			{Tld: "p", Type: "handshake"}, {Tld: "page", Type: "gTLD"},
			{Tld: "paid", Type: "handshake"}, {Tld: "pal", Type: "handshake"},
			{Tld: "paris", Type: "gTLD"}, {Tld: "partners", Type: "gTLD"},
			{Tld: "parts", Type: "gTLD"}, {Tld: "party", Type: "gTLD"},
			{Tld: "pave", Type: "handshake"}, {Tld: "pdcst", Type: "handshake"},
			{Tld: "pe", Type: "ccTLD"}, {Tld: "performer", Type: "handshake"},
			{Tld: "pest", Type: "handshake"}, {Tld: "pgp", Type: "handshake"},
			{Tld: "ph", Type: "ccTLD"}, {Tld: "photo", Type: "gTLD"},
			{Tld: "photography", Type: "gTLD"}, {Tld: "photos", Type: "gTLD"},
			{Tld: "pics", Type: "gTLD"}, {Tld: "picture", Type: "handshake"},
			{Tld: "pictures", Type: "gTLD"}, {Tld: "pier", Type: "handshake"},
			{Tld: "pink", Type: "gTLD"}, {Tld: "pix", Type: "handshake"},
			{Tld: "piz", Type: "handshake"}, {Tld: "pizza", Type: "gTLD"},
			{Tld: "place", Type: "gTLD"}, {Tld: "places", Type: "handshake"},
			{Tld: "plaza", Type: "handshake"}, {Tld: "plumbing", Type: "gTLD"},
			{Tld: "plus", Type: "gTLD"}, {Tld: "ply", Type: "handshake"},
			{Tld: "pockets", Type: "handshake"}, {Tld: "poj", Type: "handshake"},
			{Tld: "poker", Type: "gTLD"}, {Tld: "policeman", Type: "handshake"},
			{Tld: "porn", Type: "gTLD"}, {Tld: "ppp", Type: "handshake"},
			{Tld: "praha", Type: "handshake"}, {Tld: "premio", Type: "handshake"},
			{Tld: "premium", Type: "handshake"}, {Tld: "presenter", Type: "handshake"},
			{Tld: "press", Type: "gTLD"}, {Tld: "prices", Type: "handshake"},
			{Tld: "pro", Type: "gTLD"}, {Tld: "prodazha", Type: "gTLD"},
			{Tld: "productions", Type: "gTLD"}, {Tld: "profiles", Type: "handshake"},
			{Tld: "project", Type: "handshake"}, {Tld: "properties", Type: "gTLD"},
			{Tld: "property", Type: "gTLD"}, {Tld: "protection", Type: "gTLD"},
			{Tld: "pub", Type: "gTLD"}, {Tld: "pui", Type: "handshake"},
			{Tld: "pun", Type: "handshake"}, {Tld: "pv", Type: "handshake"},
			{Tld: "pw", Type: "ccTLD"}, {Tld: "pz", Type: "handshake"},
		},
	},
	{AlphaOrder: "q",
		Tld: []Tdl{
			{Tld: "qd", Type: "handshake"}, {Tld: "qf", Type: "handshake"},
			{Tld: "qg", Type: "handshake"}, {Tld: "qh", Type: "handshake"},
			{Tld: "qk", Type: "handshake"}, {Tld: "qn", Type: "handshake"},
			{Tld: "qo", Type: "handshake"}, {Tld: "queens", Type: "handshake"},
			{Tld: "quest", Type: "gTLD"}, {Tld: "qum", Type: "handshake"},
			{Tld: "qy", Type: "handshake"},
		},
	},
	{AlphaOrder: "r",
		Tld: []Tdl{
			{Tld: "racing", Type: "gTLD"}, {Tld: "realty", Type: "gTLD"},
			{Tld: "recipes", Type: "gTLD"}, {Tld: "red", Type: "gTLD"},
			{Tld: "rehab", Type: "gTLD"}, {Tld: "reise", Type: "gTLD"},
			{Tld: "reisen", Type: "gTLD"}, {Tld: "rekt", Type: "handshake"},
			{Tld: "remember", Type: "handshake"}, {Tld: "rent", Type: "gTLD"},
			{Tld: "rentals", Type: "gTLD"}, {Tld: "repair", Type: "gTLD"},
			{Tld: "report", Type: "gTLD"}, {Tld: "republican", Type: "gTLD"},
			{Tld: "researcher", Type: "handshake"}, {Tld: "resources", Type: "handshake"},
			{Tld: "rest", Type: "gTLD"}, {Tld: "restaurant", Type: "gTLD"},
			{Tld: "review", Type: "gTLD"}, {Tld: "reviews", Type: "gTLD"},
			{Tld: "rh", Type: "handshake"}, {Tld: "rican", Type: "handshake"},
			{Tld: "rip", Type: "gTLD"}, {Tld: "rl", Type: "handshake"},
			{Tld: "rn", Type: "handshake"}, {Tld: "rocks", Type: "gTLD"},
			{Tld: "rodeo", Type: "gTLD"}, {Tld: "rogan", Type: "handshake"},
			{Tld: "row", Type: "handshake"}, {Tld: "rpgs", Type: "handshake"},
			{Tld: "rsvp", Type: "gTLD"}, {Tld: "ru.com", Type: "gTLD"},
			{Tld: "rumor", Type: "handshake"}, {Tld: "run", Type: "gTLD"},
			{Tld: "runs", Type: "handshake"}, {Tld: "rural", Type: "handshake"},
			{Tld: "russo", Type: "handshake"}, {Tld: "rust", Type: "handshake"},
			{Tld: "ryukyu", Type: "gTLD"}, {Tld: "rz", Type: "handshake"},
		},
	},
	{AlphaOrder: "s",
		Tld: []Tdl{
			{Tld: "sa.com", Type: "gTLD"}, {Tld: "saas", Type: "handshake"},
			{Tld: "sale", Type: "gTLD"}, {Tld: "sales", Type: "handshake"},
			{Tld: "samples", Type: "handshake"}, {Tld: "sarl", Type: "gTLD"},
			{Tld: "sats", Type: "handshake"}, {Tld: "say", Type: "handshake"},
			{Tld: "sbs", Type: "gTLD"}, {Tld: "school", Type: "gTLD"},
			{Tld: "schooling", Type: "handshake"}, {Tld: "schule", Type: "gTLD"},
			{Tld: "science", Type: "gTLD"}, {Tld: "sds", Type: "handshake"},
			{Tld: "se.net", Type: "gTLD"}, {Tld: "secrets", Type: "handshake"},
			{Tld: "security", Type: "gTLD"}, {Tld: "semi", Type: "handshake"},
			{Tld: "services ", Type: "gTLD"}, {Tld: "sex", Type: "gTLD"},
			{Tld: "sexblog", Type: "handshake"}, {Tld: "sexy", Type: "gTLD"},
			{Tld: "sg", Type: "ccTLD"}, {Tld: "sh", Type: "ccTLD"},
			{Tld: "sharing", Type: "handshake"}, {Tld: "shark", Type: "handshake"},
			{Tld: "shiksha", Type: "gTLD"}, {Tld: "shizzle", Type: "handshake"},
			{Tld: "shoes", Type: "gTLD"}, {Tld: "shop", Type: "gTLD"},
			{Tld: "shopping", Type: "gTLD"}, {Tld: "shoppingcart", Type: "handshake"},
			{Tld: "shortcut", Type: "handshake"}, {Tld: "shot", Type: "handshake"},
			{Tld: "show", Type: "gTLD"}, {Tld: "shp", Type: "handshake"},
			{Tld: "sig", Type: "handshake"}, {Tld: "simp", Type: "handshake"},
			{Tld: "simplicity", Type: "handshake"}, {Tld: "singles ", Type: "gTLD"},
			{Tld: "site", Type: "gTLD"}, {Tld: "ski", Type: "gTLD"},
			{Tld: "skin", Type: "gTLD"}, {Tld: "sniff", Type: "handshake"},
			{Tld: "so", Type: "ccTLD"}, {Tld: "soccer", Type: "gTLD"},
			{Tld: "social", Type: "gTLD"}, {Tld: "software", Type: "gTLD"},
			{Tld: "solar", Type: "gTLD"}, {Tld: "solution", Type: "handshake"},
			{Tld: "solutions", Type: "gTLD"}, {Tld: "sos", Type: "handshake"},
			{Tld: "southafrican", Type: "handshake"}, {Tld: "sox", Type: "handshake"},
			{Tld: "soy", Type: "gTLD"}, {Tld: "spac", Type: "handshake"},
			{Tld: "space", Type: "gTLD"}, {Tld: "specs", Type: "handshake"},
			{Tld: "squirtfiesta", Type: "handshake"}, {Tld: "src", Type: "handshake"},
			{Tld: "ssl", Type: "handshake"}, {Tld: "startup", Type: "handshake"},
			{Tld: "storage", Type: "gTLD"}, {Tld: "store", Type: "gTLD"},
			{Tld: "stream", Type: "gTLD"}, {Tld: "streamer", Type: "handshake"},
			{Tld: "studio", Type: "gTLD"}, {Tld: "study", Type: "gTLD"},
			{Tld: "style", Type: "gTLD"}, {Tld: "substack", Type: "handshake"},
			{Tld: "sucks", Type: "gTLD"}, {Tld: "supplies", Type: "gTLD"},
			{Tld: "supply", Type: "gTLD"}, {Tld: "support", Type: "gTLD"},
			{Tld: "supreme", Type: "handshake"}, {Tld: "surf", Type: "gTLD"},
			{Tld: "surgery", Type: "gTLD"}, {Tld: "sus", Type: "handshake"},
			{Tld: "swapz", Type: "handshake"}, {Tld: "sydney", Type: "gTLD"},
			{Tld: "systems", Type: "gTLD"},
		},
	},
	{AlphaOrder: "t",
		Tld: []Tdl{
			{Tld: "tao", Type: "handshake"}, {Tld: "tar", Type: "handshake"},
			{Tld: "tattoo", Type: "gTLD"}, {Tld: "tax", Type: "gTLD"},
			{Tld: "taxfree", Type: "handshake"}, {Tld: "taxi", Type: "gTLD"},
			{Tld: "team", Type: "gTLD"}, {Tld: "tech", Type: "gTLD"},
			{Tld: "techblog", Type: "handshake"}, {Tld: "technology", Type: "gTLD"},
			{Tld: "teck", Type: "handshake"}, {Tld: "teenager", Type: "handshake"},
			{Tld: "teepee", Type: "handshake"}, {Tld: "tefi", Type: "handshake"},
			{Tld: "tel", Type: "gTLD"}, {Tld: "tennis", Type: "gTLD"},
			{Tld: "ter", Type: "handshake"}, {Tld: "theater", Type: "gTLD"},
			{Tld: "theatre ", Type: "gTLD"}, {Tld: "thenerd", Type: "handshake"},
			{Tld: "tickets", Type: "gTLD"}, {Tld: "tienda", Type: "gTLD"},
			{Tld: "tips", Type: "gTLD"}, {Tld: "tires", Type: "gTLD"},
			{Tld: "tni", Type: "handshake"}, {Tld: "to", Type: "ccTLD"},
			{Tld: "today", Type: "gTLD"}, {Tld: "token", Type: "handshake"},
			{Tld: "tokyo", Type: "gTLD"}, {Tld: "tools", Type: "gTLD"},
			{Tld: "top", Type: "gTLD"}, {Tld: "tours", Type: "gTLD"},
			{Tld: "town", Type: "gTLD"}, {Tld: "toys", Type: "gTLD"},
			{Tld: "trade", Type: "gTLD"}, {Tld: "trader", Type: "handshake"},
			{Tld: "training", Type: "gTLD"}, {Tld: "trans", Type: "handshake"},
			{Tld: "travel", Type: "gTLD"}, {Tld: "trekking ", Type: "handshake"},
			{Tld: "tricks", Type: "handshake"}, {Tld: "troll", Type: "handshake"},
			{Tld: "tube", Type: "gTLD"}, {Tld: "tuber", Type: "handshake"},
			{Tld: "turtles", Type: "handshake"}, {Tld: "tutorial", Type: "handshake"},
			{Tld: "tv", Type: "ccTLD"}, {Tld: "tx", Type: "handshake"},
		},
	},
	{AlphaOrder: "u",
		Tld: []Tdl{
			{Tld: "u2", Type: "handshake"}, {Tld: "ud", Type: "handshake"},
			{Tld: "ue", Type: "handshake"}, {Tld: "uf", Type: "handshake"},
			{Tld: "uge", Type: "handshake"}, {Tld: "uk", Type: "ccTLD"},
			{Tld: "uk.com", Type: "gTLD"}, {Tld: "uk.net", Type: "gTLD"},
			{Tld: "uk3", Type: "handshake"}, {Tld: "ultimate", Type: "handshake"},
			{Tld: "umo", Type: "handshake"}, {Tld: "underground", Type: "handshake"},
			{Tld: "underworld", Type: "handshake"}, {Tld: "unit", Type: "handshake"},
			{Tld: "universe", Type: "handshake"}, {Tld: "university", Type: "gTLD"},
			{Tld: "unlock", Type: "handshake"}, {Tld: "uno", Type: "gTLD"},
			{Tld: "us", Type: "ccTLD"}, {Tld: "us.com", Type: "ccTLD"},
			{Tld: "us.org", Type: "ccTLD"}, {Tld: "us3", Type: "handshake"},
			{Tld: "use", Type: "handshake"}, {Tld: "uui", Type: "handshake"},
			{Tld: "uzr", Type: "handshake"},
		},
	},
	{AlphaOrder: "v",
		Tld: []Tdl{
			{Tld: "vacations", Type: "gTLD"}, {Tld: "valley", Type: "handshake"},
			{Tld: "vase", Type: "handshake"}, {Tld: "vc", Type: "ccTLD"},
			{Tld: "vegas", Type: "gTLD"}, {Tld: "ventures", Type: "ccTLD"},
			{Tld: "vet", Type: "gTLD"}, {Tld: "viajes ", Type: "gTLD"},
			{Tld: "video", Type: "handshake"}, {Tld: "vie", Type: "handshake"},
			{Tld: "viewer", Type: "handshake"}, {Tld: "villas", Type: "gTLD"},
			{Tld: "vin", Type: "gTLD"}, {Tld: "vip", Type: "gTLD"},
			{Tld: "vision", Type: "gTLD"}, {Tld: "visit", Type: "handshake"},
			{Tld: "vj", Type: "handshake"}, {Tld: "vlog", Type: "handshake"},
			{Tld: "vodka", Type: "gTLD"}, {Tld: "voice", Type: "gTLD"},
			{Tld: "vote", Type: "gTLD"}, {Tld: "voting", Type: "gTLD"},
			{Tld: "voto", Type: "gTLD"}, {Tld: "voyage", Type: "gTLD"},
			{Tld: "vq", Type: "handshake"}, {Tld: "vuo", Type: "handshake"},
		},
	},
	{AlphaOrder: "w",
		Tld: []Tdl{
			{Tld: "w33d", Type: "handshake"}, {Tld: "w3b", Type: "handshake"},
			{Tld: "w3n", Type: "handshake"}, {Tld: "w8", Type: "handshake"},
			{Tld: "wales", Type: "gTLD"}, {Tld: "wasabi", Type: "handshake"},
			{Tld: "watch", Type: "gTLD"}, {Tld: "wave ", Type: "handshake"},
			{Tld: "wc", Type: "handshake"}, {Tld: "we3", Type: "handshake"},
			{Tld: "web4", Type: "handshake"}, {Tld: "webartist", Type: "handshake"},
			{Tld: "webcam", Type: "gTLD"}, {Tld: "webdesigner", Type: "handshake"},
			{Tld: "website", Type: "gTLD"}, {Tld: "websites", Type: "handshake"},
			{Tld: "wedding", Type: "gTLD"}, {Tld: "wh", Type: "handshake"},
			{Tld: "whitepaper", Type: "handshake"}, {Tld: "wiki", Type: "gTLD"},
			{Tld: "win", Type: "gTLD"}, {Tld: "wine", Type: "gTLD"},
			{Tld: "wj", Type: "handshake"}, {Tld: "wl", Type: "handshake"},
			{Tld: "won", Type: "handshake"}, {Tld: "work", Type: "gTLD"},
			{Tld: "world", Type: "gTLD"}, {Tld: "worldtour", Type: "handshake"},
			{Tld: "wq", Type: "handshake"}, {Tld: "wr", Type: "handshake"},
			{Tld: "ws", Type: "ccTLD"}, {Tld: "wt", Type: "handshake"},
			{Tld: "wtf", Type: "gTLD"},
		},
	},
	{AlphaOrder: "x",
		Tld: []Tdl{
			{Tld: "x00m", Type: "handshake"}, {Tld: "x2", Type: "handshake"},
			{Tld: "xa", Type: "handshake"}, {Tld: "xb", Type: "handshake"},
			{Tld: "xc", Type: "handshake"}, {Tld: "xcam", Type: "handshake"},
			{Tld: "xf", Type: "handshake"}, {Tld: "xg ", Type: "handshake"},
			{Tld: "xi", Type: "handshake"}, {Tld: "xk", Type: "handshake"},
			{Tld: "xn--3ds443g", Type: "gTLD"}, {Tld: "xn--5o8h", Type: "handshake"},
			{Tld: "xn--6ca", Type: "handshake"}, {Tld: "xn--6frz82g ", Type: "gTLD"},
			{Tld: "xn--dei", Type: "handshake"}, {Tld: "xn--dp8h", Type: "handshake"},
			{Tld: "xn--e77hhb", Type: "handshake"}, {Tld: "xn--g6h", Type: "handshake"},
			{Tld: "xn--pei", Type: "handshake"}, {Tld: "xn--rci", Type: "handshake"},
			{Tld: "xq", Type: "handshake"}, {Tld: "xr", Type: "handshake"},
			{Tld: "xxx", Type: "gTLD"}, {Tld: "xxxx", Type: "handshake"},
			{Tld: "xyz", Type: "gTLD"},
		},
	},
	{AlphaOrder: "y",
		Tld: []Tdl{
			{Tld: "yachts", Type: "gTLD"}, {Tld: "yb", Type: "handshake"},
			{Tld: "yd", Type: "handshake"}, {Tld: "year", Type: "handshake"},
			{Tld: "yh", Type: "handshake"}, {Tld: "yj", Type: "handshake"},
			{Tld: "yo", Type: "handshake"}, {Tld: "yoga ", Type: "gTLD"},
			{Tld: "yokohama", Type: "gTLD"}, {Tld: "yol", Type: "handshake"},
			{Tld: "yolo", Type: "handshake"}, {Tld: "yq", Type: "handshake"},
			{Tld: "yummy", Type: "handshake"}, {Tld: "yz ", Type: "handshake"},
			{Tld: "yzx", Type: "handshake"},
		},
	},
	{AlphaOrder: "z",
		Tld: []Tdl{
			{Tld: "za.com", Type: "gTLD"}, {Tld: "zc", Type: "handshake"},
			{Tld: "zen", Type: "handshake"}, {Tld: "zh", Type: "handshake"},
			{Tld: "zone", Type: "gTLD"}, {Tld: "zoy", Type: "handshake"},
			{Tld: "zp", Type: "handshake"}, {Tld: "zs ", Type: "handshake"},
			{Tld: "zug", Type: "handshake"}, {Tld: "zx", Type: "handshake"},
			{Tld: "zy", Type: "handshake"},
		},
	},
}
